name: Vercel Production Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Vercel CLI
      - name: Install Vercel CLI
        run: npm install --global vercel

      # Step 3: Pull Vercel Environment Information (optional but useful)
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      # Step 4: Install project dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Build the project (this can be optional as Vercel builds it automatically)
      - name: Build the project
        run: npm run build

      # Step 6: Deploy the project to Vercel
      - name: Deploy to Vercel Production
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}