import Footer from "../components/footer";
import Navbar from "../components/navbar";

const Disclaimer=()=>{
    return (
        <>
            <Navbar/>
            <div className="container-fluid p-0">
                <div className="flex justify-center items-center text-center mt-6">
                    <div className="w-full sm:w-[600px] lg:w-[800px] mt-6">
                        <div className="mt-5 w-full lg:max-w-[1320px] mx-auto p-4">
                            <h1 className="text-4xl font-bold mt-7">Disclaimer</h1>
                        </div>
                    </div>
                </div>
                <div className="flex flex-col w-full lg:max-w-[1200px] mx-auto p-7 mb-20">
                    <div className="bg-slate-100 shadow-xl p-5 border rounded-lg">
                        <div className="bg-white shadow-md p-4">
                            <h1 className="text-3xl font-bold">Purpose of the Tool</h1>
                            <p className="text-md mt-3 text-justify">The [Your Rewriter Tool Name] is designed to assist users in rephrasing, rewriting, and enhancing written content. The tool is intended for a variety of uses, including but not limited to academic writing, professional documents, and personal projects. It aims to provide users with an efficient way to generate alternative phrasing and improve the clarity and quality of their text. However, the output generated is dependent on the input provided, and users should be aware that the results may vary based on context and complexity.</p>
                        </div>
                        <div className="bg-white shadow-md p-4 mt-4">
                            <h1 className="text-3xl font-bold">Originality of Content</h1>
                            <p className="text-md mt-3 text-justify">While [Your Rewriter Tool Name] strives to produce original content, it is important to note that users are responsible for ensuring the uniqueness of the final output. The tool uses algorithms to transform the input text, but there is no guarantee that the rewritten content will be completely original or free from similarities to existing works. Users should conduct their own originality checks, especially when submitting content for academic or professional purposes, to avoid issues related to copyright infringement or plagiarism.</p>
                        </div>
                        <div className="bg-white shadow-md p-4 mt-4">
                            <h1 className="text-3xl font-bold">No Liability for Content Use</h1>
                            <p className="text-md mt-3 text-justify">[Your Company Name], along with its affiliates, employees, and agents, shall not be held liable for any damages, losses, or legal repercussions that may arise from the use of content generated by [Your Rewriter Tool Name]. This includes, but is not limited to, claims of copyright infringement, plagiarism, or any other legal issues that may occur as a result of using the rewritten content. By using this tool, users acknowledge that they are doing so at their own risk and that they will not hold [Your Company Name] responsible for any adverse outcomes.</p>
                        </div>
                        <div className="bg-white shadow-md p-4 mt-4">
                            <h1 className="text-3xl font-bold"> User Responsibility</h1>
                            <p className="text-md mt-3 text-justify">Users of [Your Rewriter Tool Name] are solely responsible for reviewing, editing, and ensuring the appropriateness of the rewritten content prior to any use. It is essential that users apply their personal judgment and discretion in evaluating the output, as the tool may not fully understand context, tone, or nuance. This includes making necessary changes to ensure that the final content aligns with the user’s intent and is suitable for the intended audience.</p>
                        </div>
                        <div className="bg-white shadow-md p-4 mt-4">
                            <h1 className="text-3xl font-bold">Data Privacy and Security</h1>
                            <p className="text-md mt-3 text-justify">We take data privacy and security seriously. When users access [Your Rewriter Tool Name], we may collect and process information, including the text inputted into the tool and usage data. This information is used primarily to enhance the user experience and improve our services. We are committed to safeguarding personal information and will not share it with third parties without the user’s explicit consent. For more information on how we handle user data, please refer to our Privacy Policy, which provides detailed information on data collection, usage, and protection practices.</p>
                        </div>
                        <div className="bg-white shadow-md p-4 mt-4">
                            <h1 className="text-3xl font-bold">Restrictions on Use</h1>
                            <p className="text-md mt-3 text-justify">The content generated by [Your Rewriter Tool Name] is intended solely for personal use. Users are prohibited from using the output for commercial purposes without obtaining prior written consent from [Your Company Name]. Additionally, users must refrain from using the tool for illegal or unethical activities, including academic dishonesty or any fraudulent practices. Violating these restrictions may result in the termination of access to the tool and potential legal action.</p>
                        </div>
                        <div className="bg-white shadow-md p-4 mt-4">
                            <h1 className="text-3xl font-bold">Changes to the Disclaimer</h1>
                            <p className="text-md mt-3 text-justify">[Your Company Name] reserves the right to modify or update this disclaimer at any time without prior notice. Users are encouraged to periodically review this disclaimer to remain informed of any changes. Continued use of [Your Rewriter Tool Name] after any modifications indicates acceptance of the revised terms. If any significant changes are made, we will strive to notify users through our website or via email.</p>
                        </div>
                        <div className="bg-white shadow-md p-4 mt-4">
                            <h1 className="text-3xl font-bold">Contact Information</h1>
                            <p className="mt-5">
                                <i class="fa-solid fa-phone text-blue-700"></i><span className="ml-5">111-222-333</span>
                            </p>
                            <p className="mt-5">
                            <i class="fa-solid fa-envelope text-yellow-600"></i><span className="ml-5">paraWriter@gmail.com</span>
                            </p>
                        </div>
                    </div>
                    
                </div>
            </div>
            <Footer/>
        </>
    );
}
export default Disclaimer;